# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='imageCaptioning',
  syntax='proto3',
  serialized_pb=_b('\n\ntest.proto\x12\x0fimageCaptioning\".\n\x07Request\x12\x11\n\timageData\x18\x01 \x01(\x0c\x12\x10\n\x08\x61udio_id\x18\x02 \x01(\t\"1\n\x08Response\x12\x11\n\taudioData\x18\x01 \x01(\x0c\x12\x12\n\nresultText\x18\x02 \x01(\t2a\n\x13ImageCaptionService\x12J\n\rDataStreaming\x12\x18.imageCaptioning.Request\x1a\x19.imageCaptioning.Response\"\x00(\x01\x30\x01\x42\x30\n\x1bio.grpctest.imageCaptioningB\x0fImageCaptioningP\x01\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='imageCaptioning.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageData', full_name='imageCaptioning.Request.imageData', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio_id', full_name='imageCaptioning.Request.audio_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=77,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='imageCaptioning.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='audioData', full_name='imageCaptioning.Response.audioData', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resultText', full_name='imageCaptioning.Response.resultText', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:imageCaptioning.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:imageCaptioning.Response)
  ))
_sym_db.RegisterMessage(Response)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpctest.imageCaptioningB\017ImageCaptioningP\001'))

_IMAGECAPTIONSERVICE = _descriptor.ServiceDescriptor(
  name='ImageCaptionService',
  full_name='imageCaptioning.ImageCaptionService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=130,
  serialized_end=227,
  methods=[
  _descriptor.MethodDescriptor(
    name='DataStreaming',
    full_name='imageCaptioning.ImageCaptionService.DataStreaming',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGECAPTIONSERVICE)

DESCRIPTOR.services_by_name['ImageCaptionService'] = _IMAGECAPTIONSERVICE

# @@protoc_insertion_point(module_scope)
